// GERADO automaticamente a partir de logos/acervo. Slug da pasta -> nome de exibição do projeto.
export const CORP_PROJECT_NAMES: Record<string, string> = {
  "181-carnes": "181 Carnes",
  "a-nordestina": "A Nordestina",
  "alice": "Alice",
  "aline-isidoro": "Aline Isidoro",
  "alita-lima": "Alita Lima",
  "aluria": "Alúria",
  "ampla-formula": "Ampla Fórmula",
  "and-branding": "AND Branding",
  "ao-lado": "Ao Lado",
  "artconcept": "ArtConcept",
  "atelie-das-cores": "Ateliê das Cores",
  "aurois": "Aurois",
  "ays": "AYS",
  "ayty": "Ayty",
  "b-personaliza": "B Personaliza",
  "beauty-fast": "Beauty Fast",
  "bemps": "Bemps",
  "blume": "Blume",
  "bono-quali": "Bono Quali",
  "bora-brincar": "Bora Brincar",
  "boutique-doce": "Boutique Doce",
  "cabeca-de-cuia": "Cabeça de Cuia",
  "camila-conrado": "Camila Conrado",
  "cardio-086": "Cardio 086",
  "carla-rufino": "Carla Rufino",
  "carlos-castro": "Carlos Castro",
  "carol-leopoldino": "Carol Leopoldino",
  "carol-morais": "Carol Morais",
  "casa-afeto": "Casa Afeto",
  "casa-guara": "Casa Guará",
  "casa-luzia": "Casa Luzia",
  "casa-mubless": "Casa Mubless",
  "casinha-da-lulu": "Casinha da Lulu",
  "cecile": "Cecile",
  "civicbox": "CivicBox",
  "coelho-de-melo": "Coelho de Melo",
  "conecc": "Conecc",
  "conecta-piaui": "Conecta Piauí",
  "contar": "Contar",
  "debora-moura": "Débora Moura",
  "detura": "Détura",
  "don-vier": "Don Vier",
  "dra-ana-tecla": "Dra. Ana Tecla",
  "dra-julia-beatriz": "Dra. Júlia Beatriz",
  "dstk": "DSTK",
  "eco-adventure-tour": "Eco Adventure Tour",
  "eco-travels": "Eco Travels",
  "efeito-caracois": "Efeito Caracóis",
  "el-mel": "El Mel",
  "elak-studio": "Elak Studio",
  "enfacilita": "Enfacilita",
  "enom": "Enom",
  "espaco-nasar": "Espaço Nasar",
  "evoluauto": "EvoluAuto",
  "farmampla": "Farmampla",
  "felipe-daniel": "Felipe Daniel",
  "fundacao-entrecultura": "Fundação Entrecultura",
  "gabrielly-oliveira": "Gabrielly Oliveira",
  "georgia-lau": "Geórgia Lau",
  "gestor-saude": "Gestor Saúde",
  "gotech": "Gotech",
  "graca-nobre": "Graça Nobre",
  "grupo-l-sa": "Grupo L Sá",
  "hortifrios-emporium": "Hortifrios Emporium",
  "imunibee": "Imunibee",
  "instituto-alef-franca": "Instituto Alef França",
  "jedilog": "Jedilog",
  "joao-e-maria": "João e Maria",
  "joulou": "Joulou",
  "juliana-maia": "Juliana Maia",
  "kallyanne-milhomem": "Kallyanne Milhomem",
  "karnacast": "Karnacast",
  "ketlin-moura-santos": "Ketlin Moura Santos",
  "lais-marcele": "Laís Marcele",
  "lampers": "Lampers",
  "larissa-almeida": "Larissa Almeida",
  "lavanderia-ininga": "Lavanderia Ininga",
  "leg": "Leg",
  "lencois-maranhenses": "Lençóis Maranhenses",
  "leticia-moura": "Letícia Moura",
  "leticia-stampa": "Letícia Stampa",
  "lia-formiga": "Lia Formiga",
  "liana-ramos": "Liana Ramos",
  "lilian-lopes": "Lilian Lopes",
  "lincla": "Lincla",
  "linka": "Linka",
  "lorena-miranda": "Lorena Miranda",
  "lp-auto-pecas": "LP Auto Peças",
  "lu-barros": "Lu Barros",
  "lw-wear": "LW Wear",
  "madureira-lorena": "Madureira Lorena",
  "maira-leite": "Maira Leite",
  "mandy": "Mandy",
  "marcia-leite": "Márcia Leite",
  "maria-rebello": "Maria Rebello",
  "mariel-marques": "Mariel Marques",
  "marina-ribeiro": "Marina Ribeiro",
  "maternize": "Maternize",
  "mb-odontologia": "MB Odontologia",
  "md-semijoias": "MD Semijoias",
  "me-arrumei": "Me Arrumei",
  "meiju-decor": "Meiju Decor",
  "mercado-do-pao": "Mercado do Pão",
  "merlin": "Merlin",
  "mirella-alencar": "Mirella Alencar",
  "modogym": "Modogym",
  "montevita": "Montevita",
  "mov-gov": "Mov Gov",
  "movense": "Movense",
  "mozzi": "Môzzi",
  "mubless": "Mubless",
  "mv-audiovisual": "MV Audiovisual",
  "na-terra-da-rainha": "Na Terra da Rainha",
  "o-encontro": "O Encontro",
  "odonto-fan": "Odonto Fan",
  "onda-laranja": "Onda Laranja",
  "otica-brasileira": "Ótica Brasileira",
  "oticas-graziela": "Óticas Graziela",
  "pao-da-hora": "Pão da Hora",
  "piaui-autos": "Piauí Autos",
  "picwind": "Picwind",
  "planejar": "Planejar",
  "programa-praticando": "Programa Praticando",
  "qg-fashion": "QG Fashion",
  "raeda-veiculos": "Raeda Veículos",
  "rav-motors": "RAV Motors",
  "regula-rizar": "Regula Rizar",
  "renata-rego": "Renata Rêgo",
  "renata-semijoias": "Renata Semijoias",
  "sante": "Santé",
  "sara-rocha": "Sara Rocha",
  "sattva": "Sattva",
  "sayd-sara": "Sayd Sara",
  "sebastiao-bisneto": "Sebastião Bisneto",
  "sete-sentidos": "Sete Sentidos",
  "sg-cenografia": "SG Cenografia",
  "silas-tv": "Silas TV",
  "solutta": "Solutta",
  "soneart": "Soneart",
  "sortie": "Sortie",
  "sou-formula": "Sou+ Fórmula",
  "soul-mistica": "Soul Mística",
  "spyrit": "Spyrit",
  "straw-berry": "Straw Berry",
  "supra": "Supra",
  "tannandra-sampaio": "Tannandra Sampaio",
  "teto": "Têto",
  "thay-piauilino": "Thay Piauilino",
  "torratta": "Torratta",
  "tres-marias": "Três Marias",
  "valflores": "Valflores",
  "vanessa-hair": "Vanessa Hair",
  "vectors": "Vectors",
  "vila": "Vila",
  "vitoria-castelo-branco": "Vitória Castelo Branco",
  "vitrina": "Vitrina",
  "vittalia": "Vittalia",
  "vive": "Vivé",
  "viver-melhor": "Viver Melhor",
  "wallarts": "Wallarts",
  "xtanne": "Xtanne",
  "zurich": "Zurich",
};
